subinclude("//build/defs:sh")

sh_script(
    name = "changes",
    main = "changes.sh",
    visibility = ["PUBLIC"],
    deps = [
        "//build/util",
        "//third_party/sh:shflags",
    ],
)
